apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: night-skies
  name: night-skies-pvc
  namespace: night-skies
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 2Gi